[package]
name = "my_rust_wasm_app"
version = "0.1.0"
authors = ["Your Name <your.email@example.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"

[features]
wee_alloc = ["wee_alloc"]

[dependencies.wee_alloc]
version = "0.4.5"
optional = true
